### ISSUE TITLE
Feature: LMS Text-to-Speech

### ISSUE THREAD

**Issue by Fermain** [Fermain/-mollify#25]
LMS requires a TTS module to provide audio for student users reading through content. An existing `npm` package exists called `mollify-tts` that uses browser-based local TTS.

Although this is cheap and reasonably reliable, results vary on different operating systems and the quality is average. As a team we should explore other options such as ElevenLabs API for these files.

**Comment by Fermain** [comment]
This should be exposed as a component `Reader` or via Molly

**Comment by pretzL** [comment]
#49 Adds a potential MVP for the Molly TTS system. This TTS system parses markdown into text and uses the ElevenLabs API to read it into an audio file. This file is then presented to the Reader component, allowing markdown pages to be read to the user. This can be considered a MVP since most. if not all, of the intended functionality is there. What remains is mainly styling and parsing and reading the existing content.

Perhaps a plan should be created to assess what a new institution would have to go through in order to have all their content read? ElevenLabs can become quite expensive for a larger institution.

**Comment by Fermain** [comment]
Future tasks for a fallback to browser based TTS would be nice too

**Comment by pretzL** [comment]
> Elevenlabs is a placeholder service until I have my PC running properly. Then we can use Bark as much as we like. It will be slower than EL and probably not such nice quality, but we can iterate and tweak it more.

Should maybe look into setting up streaming if it's much slower and worse quality. Either way, loading/unloading these files is likely going to take time - for the end user as well - but slower doesn't need to be a problem since parsing is only doing to be done once unless the content changes.

**Comment by Fermain** [comment]
> > Elevenlabs is a placeholder service until I have my PC running properly. Then we can use Bark as much as we like. It will be slower than EL and probably not such nice quality, but we can iterate and tweak it more.
> 
> Should maybe look into setting up streaming if it's much slower and worse quality. Either way, loading/unloading these files is likely going to take time - for the end user as well - but slower doesn't need to be a problem since parsing is only doing to be done once unless the content changes.

AFAIK modern browsers will automatically buffer/stream and cache audio files - so I think the current implementation is fine. We shouldn't be doing JIT TTS either, it should only be done on a new PR since thats when content will change.
