### ISSUE TITLE
Feature: LMS Search

### ISSUE THREAD

**Issue by Fermain** [Fermain/-mollify#26]
LMS requires a dynamic search functionality that allows for users to search through the existing content based on keywords.

Each entity contains a `tags` property within frontmatter than can be indexed for search.

LMS search should be built upon an existing solution such as ElasticSearch or GraphQL.

**Comment by Anclagen** [comment]
Upon some investigations we have have opted to use a client side search package called fuse.js, rather than requiring a user to setup an external search server with ElasticSearch or RediSearch.

This can be used to search title, tags and the lesson content to find related items to the search query.

It also has a selection of operands out of the box that can be used, although these don't entirely work as advertised so some additional manipulation search teams and filtering of the results is likely to be required. A basic implementation of fuse was merged into the search-dev branch with PR #47 

Future aims; 
- Fancy UI, for users to select filtering options and exclude terms.
- Leet input, allowing users to input syntax into the search bar which correlates to filter options.

**Comment by Anclagen** [comment]
Basic search implementation with some simple filtering for types merged into main.

- Look ahead search bar added
- Search page with basic UI options added.

**Comment by Anclagen** [comment]
This can be considered near complete with the addition of code for #58
